# Generated by Django 4.2.2 on 2023-08-02 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSurface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Povrch materialu',
                'verbose_name_plural': 'Povrchy materialu',
            },
        ),
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('capacity', models.FloatField()),
                ('load_weight', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Paleta',
                'verbose_name_plural': 'Palety',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Akost materialu',
                'verbose_name_plural': 'Materialove akosti',
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.FloatField()),
                ('size_x', models.IntegerField()),
                ('size_y', models.IntegerField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=128, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='Core.rawmaterial')),
                ('surface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surface', to='Core.materialsurface')),
            ],
            options={
                'verbose_name': 'Plech',
                'verbose_name_plural': 'Plechy',
            },
        ),
        migrations.CreateModel(
            name='PaletteSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=128, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created', to=settings.AUTH_USER_MODEL)),
                ('palette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.palette')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.sheet')),
            ],
            options={
                'verbose_name': 'Plech na palete',
                'verbose_name_plural': 'Plechy na palete',
            },
        ),
        migrations.AddField(
            model_name='palette',
            name='sheets',
            field=models.ManyToManyField(blank=True, related_name='palette_sheet', through='Core.PaletteSheet', to='Core.sheet'),
        ),
    ]
