# Generated by Django 4.2.2 on 2023-08-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_materialissue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palette',
            name='sheets',
        ),
        migrations.RemoveField(
            model_name='palettesheet',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='palettesheet',
            name='palette',
        ),
        migrations.RemoveField(
            model_name='palettesheet',
            name='sheet',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='material',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='surface',
        ),
        migrations.DeleteModel(
            name='MaterialIssue',
        ),
        migrations.DeleteModel(
            name='MaterialSurface',
        ),
        migrations.DeleteModel(
            name='Palette',
        ),
        migrations.DeleteModel(
            name='PaletteSheet',
        ),
        migrations.DeleteModel(
            name='RawMaterial',
        ),
        migrations.DeleteModel(
            name='Sheet',
        ),
    ]
