# Generated by Django 4.2.2 on 2023-06-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0002_palette_load_weight_alter_palette_capacity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material", models.CharField(max_length=64)),
                ("surface", models.CharField(max_length=32)),
                ("tickness", models.FloatField()),
                ("size_x", models.IntegerField()),
                ("size_y", models.IntegerField()),
                ("weight", models.FloatField()),
            ],
        ),
    ]
