# Generated by Django 4.2.2 on 2023-06-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0003_sheet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sheet",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
