# Generated by Django 4.2.2 on 2023-06-10 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0004_alter_sheet_weight"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sheet",
            options={"verbose_name": "Plech", "verbose_name_plural": "Plechy"},
        ),
        migrations.CreateModel(
            name="PaletteSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "palette",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Core.palette"
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Core.sheet"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="palette",
            name="sheets",
            field=models.ManyToManyField(
                blank=True,
                related_name="palette_sheet",
                through="Core.PaletteSheet",
                to="Core.sheet",
            ),
        ),
    ]
