# Generated by Django 4.2.2 on 2023-07-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_sheet_options_palettesheet_palette_sheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='note',
            field=models.CharField(default=' ', max_length=128),
            preserve_default=False,
        ),
    ]
