# Generated by Django 4.2.2 on 2023-07-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_sheet_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='palettesheet',
            name='note',
            field=models.CharField(default=' ', max_length=128),
            preserve_default=False,
        ),
    ]
