# Generated by Django 4.2.2 on 2023-07-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_palettesheet_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='note',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
