# Generated by Django 4.2.2 on 2023-08-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=64)),
                ('sheets', models.ManyToManyField(related_name='material_issue_sheet', to='Rack.palettesheet')),
            ],
            options={
                'verbose_name': 'Materialova vydajka',
                'verbose_name_plural': 'Materialove vydajky',
            },
        ),
    ]
